# sample netlify.toml
[build]
  base = "site/"
  command = "npm run build"
  functions = "site/src/functions/" # netlify dev uses this to know where to scaffold and serve your functions
  publish = "site/build/unbundled/"

# note: each of these fields are OPTIONAL
[dev]
  base = "site/"
  command = "npm run dev" # Command to start your dev server
  port = 8000 # Port that the dev server will be listening on
  functionsPort = 34567 # port for functions server
  targetPort = 8000 # Port of target app server
  publish = "site/build/unbundled/" # If you use a _redirect file, provide the path to your static content folder

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
